# This file which serves to creates a pdf report after running OOD detection has been generated by Claude

from __future__ import annotations

import os
import textwrap
import warnings
from io import StringIO
from pathlib import Path
from typing import Dict, List, Optional, Sequence

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

# ReportLab imports
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    Image,
    NextPageTemplate,
    PageBreak,
    PageTemplate,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.platypus.flowables import HRFlowable


# ---------------------------------------------------------------------------
# Style helpers
# ---------------------------------------------------------------------------

DARK   = colors.HexColor("#1a1a2e")
ACCENT = colors.HexColor("#16213e")
LIGHT  = colors.HexColor("#e8e8f0")
GREEN  = colors.HexColor("#2ecc71")
RED    = colors.HexColor("#e74c3c")
BLUE   = colors.HexColor("#3498db")
GREY   = colors.HexColor("#95a5a6")


def _make_styles():
    base = getSampleStyleSheet()
    styles = {}

    styles["title"] = ParagraphStyle(
        "ReportTitle",
        parent    = base["Title"],
        fontSize  = 22,
        textColor = DARK,
        spaceAfter = 6,
        alignment = TA_CENTER,
    )
    styles["subtitle"] = ParagraphStyle(
        "Subtitle",
        parent    = base["Normal"],
        fontSize  = 11,
        textColor = GREY,
        alignment = TA_CENTER,
        spaceAfter = 4,
    )
    styles["h1"] = ParagraphStyle(
        "H1",
        parent      = base["Heading1"],
        fontSize    = 14,
        textColor   = DARK,
        borderPad   = (0, 0, 4, 0),
        spaceBefore = 14,
        spaceAfter  = 4,
    )
    styles["h2"] = ParagraphStyle(
        "H2",
        parent      = base["Heading2"],
        fontSize    = 11,
        textColor   = ACCENT,
        spaceBefore = 10,
        spaceAfter  = 3,
    )
    styles["body"] = ParagraphStyle(
        "Body",
        parent    = base["Normal"],
        fontSize  = 9,
        leading   = 14,
        textColor = colors.black,
    )
    styles["mono"] = ParagraphStyle(
        "Mono",
        parent     = base["Code"],
        fontSize   = 8,
        leading    = 12,
        textColor  = ACCENT,
        fontName   = "Courier",
        backColor  = colors.HexColor("#f4f4f8"),
        borderPad  = 4,
        spaceAfter = 4,
    )
    styles["caption"] = ParagraphStyle(
        "Caption",
        parent    = base["Normal"],
        fontSize  = 8,
        textColor = GREY,
        alignment = TA_CENTER,
        spaceAfter = 8,
    )
    return styles


def _metric_table(rows: List[List], col_widths=None) -> Table:
    """Styled two-column metric table."""
    t = Table(rows, colWidths=col_widths or [8 * cm, 6 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND",  (0, 0), (-1, 0), DARK),
        ("TEXTCOLOR",   (0, 0), (-1, 0), colors.white),
        ("FONTNAME",    (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",    (0, 0), (-1, 0), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT]),
        ("FONTSIZE",    (0, 1), (-1, -1), 9),
        ("GRID",        (0, 0), (-1, -1), 0.25, GREY),
        ("TOPPADDING",  (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    return t


def _safe_image(path: str, max_width: float, max_height: float) -> Optional[Image]:
    """Load image only if file exists and is non-empty."""
    if not path or not os.path.isfile(path) or os.path.getsize(path) == 0:
        return None
    try:
        img = Image(path)
        ratio = min(max_width / img.imageWidth, max_height / img.imageHeight)
        img.drawWidth  = img.imageWidth  * ratio
        img.drawHeight = img.imageHeight * ratio
        return img
    except Exception:
        return None


# ---------------------------------------------------------------------------
# Header / footer callbacks
# ---------------------------------------------------------------------------

def _make_page_callbacks(method_name: str, datetime_tag: str):
    def _header_footer(canvas, doc):
        canvas.saveState()
        w, h = A4
        # header bar
        canvas.setFillColor(DARK)
        canvas.rect(0, h - 1.2 * cm, w, 1.2 * cm, fill=1, stroke=0)
        canvas.setFillColor(colors.white)
        canvas.setFont("Helvetica-Bold", 9)
        canvas.drawString(1 * cm, h - 0.85 * cm, f"OOD Evaluation Report  |  {method_name}")
        canvas.setFont("Helvetica", 8)
        canvas.drawRightString(w - 1 * cm, h - 0.85 * cm, datetime_tag)
        # footer
        canvas.setFillColor(GREY)
        canvas.setFont("Helvetica", 7)
        canvas.drawCentredString(w / 2, 0.6 * cm, f"Page {doc.page}")
        canvas.restoreState()

    return _header_footer


# ---------------------------------------------------------------------------
# Main class
# ---------------------------------------------------------------------------

class OODReport:
    """
    Build a PDF report from an OODMetrics object.

    Parameters
    ----------
    metrics    : a computed OODMetrics instance
    output_dir : directory where the PDF (and temporary figures) will be saved
    """

    def __init__(self, metrics, output_dir: str):
        from utils.metrics_utils import OODMetrics  # local import to avoid circular deps
        if not metrics._computed:
            raise RuntimeError("metrics.compute() must be called before building a report.")
        self.metrics    = metrics
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)
        self._fig_dir   = os.path.join(output_dir, "_report_figs")
        os.makedirs(self._fig_dir, exist_ok=True)

    # ------------------------------------------------------------------

    def build(
        self,
        dataset=None,
        main_config:    Optional[Dict] = None,
        dataset_config: Optional[Dict] = None,
        ood_config:     Optional[Dict] = None,
        method_name:    str = "OOD Method",
        extra_figures:  Optional[Sequence[str]] = None,
    ) -> str:
        """
        Assemble and save the PDF report.

        Parameters
        ----------
        dataset        : dataset object exposing .df, .data_train, .data_val,
                         .data_test, .n_classes(), as used in print_infos().
        main_config    : dict – must contain 'name'.
        dataset_config : dict – must contain 'data_dir' and 'data_file'.
        ood_config     : dict – must contain 'setup'.
        method_name    : human-readable OOD method label.
        extra_figures  : list of image paths to append as an extra section.

        Returns
        -------
        str : path to the saved PDF.
        """
        m          = self.metrics
        styles     = _make_styles()
        story      = []
        page_w     = A4[0] - 4 * cm   # usable width
        tag        = m.datetime_tag

        # ---- generate standard figures ----------------------------------
        hist_path = m.plot_score_histogram(self._fig_dir, method_name)
        roc_path  = m.plot_roc_curve(self._fig_dir, method_name)
        pr_path   = m.plot_pr_curve(self._fig_dir, method_name)
        cm_path   = m.plot_confusion_matrix(self._fig_dir)
        f1_path   = m.plot_per_class_bars(self._fig_dir)

        # ==================================================================
        # TITLE PAGE
        # ==================================================================
        story.append(Spacer(1, 2 * cm))
        story.append(Paragraph("OOD Evaluation Report", styles["title"]))
        story.append(Paragraph(f"Method: <b>{method_name}</b>", styles["subtitle"]))
        story.append(Paragraph(f"Dataset: {m.dataset_name}  |  Setup: {m.setup}", styles["subtitle"]))
        story.append(Paragraph(f"Generated: {tag}", styles["subtitle"]))
        story.append(HRFlowable(width="100%", thickness=1, color=DARK, spaceAfter=16))

        # -- Experiment metadata table ------------------------------------
        story.append(Paragraph("Experiment Configuration", styles["h1"]))

        meta_rows = [["Parameter", "Value"]]
        meta_rows += [
            ["Dataset",           m.dataset_name],
            ["Setup",             m.setup],
            ["Abundance filter",  str(m.abundance_filter)],
            ["Hierarchy level",   m.hierarchy_level or "—"],
            ["Model path",        m.model_path or "—"],
            ["Datetime tag",      tag],
        ]
        if dataset_config:
            data_path = os.path.join(
                dataset_config.get("data_dir", ""),
                dataset_config.get("data_file", ""),
            )
        if ood_config:
            meta_rows.append(["OOD config setup", ood_config.get("setup", "—")])

        story.append(_metric_table(meta_rows, col_widths=[7 * cm, page_w - 7 * cm]))
        story.append(Spacer(1, 0.5 * cm))

        # -- Dataset / split info (mirrors print_infos) -------------------
        if dataset is not None:
            story.append(Paragraph("Dataset &amp; Split Info", styles["h1"]))
            story.append(HRFlowable(width="100%", thickness=0.5, color=GREY, spaceAfter=6))

            try:
                samples = dataset.df.shape[0]
                n_ood   = int(dataset.df["OOD_flag"].sum())
                n_id    = samples - n_ood

                split_rows = [["Split / Stat", "Count", "Fraction"]]
                split_rows += [
                    ["Total samples",     str(samples), "1.000"],
                    ["Train set",         str(len(dataset.data_train)),
                     f"{len(dataset.data_train)/samples:.3f}"],
                    ["Validation set",    str(len(dataset.data_val)),
                     f"{len(dataset.data_val)/samples:.3f}"],
                    ["Test set",          str(len(dataset.data_test)),
                     f"{len(dataset.data_test)/samples:.3f}"],
                    ["OOD samples",       str(n_ood),  f"{n_ood/samples:.3f}"],
                    ["ID samples",        str(n_id),   f"{n_id/samples:.3f}"],
                ]
                story.append(_metric_table(
                    split_rows,
                    col_widths=[7 * cm, 4 * cm, 4 * cm],
                ))
                story.append(Spacer(1, 0.3 * cm))

                class_rows = [["Class count", "Value"]]
                class_rows += [
                    ["Total classes",       str(dataset.n_classes("all"))],
                    ["Classes in OOD",      str(dataset.n_classes("ood"))],
                    ["Classes in ID",       str(dataset.n_classes("id"))],
                    ["Train set classes",   str(len(dataset.data_train.get_labels().unique()))],
                    ["Val set classes",     str(len(dataset.data_val.get_labels().unique()))],
                    ["Test set classes",    str(len(dataset.data_test.get_labels().unique()))],
                ]
                story.append(_metric_table(class_rows))
            except Exception as exc:
                story.append(Paragraph(
                    f"<i>(Dataset info unavailable: {exc})</i>", styles["body"]
                ))

        story.append(PageBreak())

        # ==================================================================
        # OOD METRICS
        # ==================================================================
        story.append(Paragraph("OOD Detection Metrics", styles["h1"]))
        story.append(HRFlowable(width="100%", thickness=0.5, color=GREY, spaceAfter=6))

        om = m.ood_metrics
        ood_rows = [["Metric", "Value"]]
        ood_rows += [
            ["AUROC",                      f"{om['auroc']:.4f}"],
            ["FPR @ 95% TPR",              f"{om['fpr95']:.4f}"],
            ["AUPR (in-distribution)",     f"{om['aupr_in']:.4f}"],
            ["AUPR (out-of-distribution)", f"{om['aupr_out']:.4f}"],
            ["Balanced Accuracy (OOD)",    f"{om['bal_acc_ood']:.4f}"],
            ["Decision threshold",         f"{om['threshold']:.4f}"],
        ]
        story.append(_metric_table(ood_rows))
        story.append(Spacer(1, 0.5 * cm))

        # Score histogram + ROC side by side
        img_hist = _safe_image(hist_path, 8.5 * cm, 5.5 * cm)
        img_roc  = _safe_image(roc_path,  8.5 * cm, 5.5 * cm)
        if img_hist and img_roc:
            row = Table([[img_hist, img_roc]], colWidths=[9 * cm, 9 * cm])
            row.setStyle(TableStyle([("ALIGN", (0, 0), (-1, -1), "CENTER")]))
            story.append(row)
            story.append(Paragraph(
                "Left: score distributions for ID and OOD samples.  "
                "Right: ROC curve with FPR@95 marker.",
                styles["caption"],
            ))

        # PR curve
        img_pr = _safe_image(pr_path, 10 * cm, 7 * cm)
        if img_pr:
            story.append(img_pr)
            story.append(Paragraph("Precision-Recall curve (in-distribution positive).", styles["caption"]))

        story.append(PageBreak())

        # ==================================================================
        # ID CLASSIFICATION METRICS
        # ==================================================================
        story.append(Paragraph("ID Classification Metrics", styles["h1"]))
        story.append(HRFlowable(width="100%", thickness=0.5, color=GREY, spaceAfter=6))

        ic = m.id_metrics
        id_rows = [["Metric", "Min", "Median", "Mean", "Max"]]
        for stat_name in ("precision", "recall", "f1"):
            s = ic[stat_name]
            id_rows.append([
                stat_name.capitalize(),
                f"{s['min']:.4f}",
                f"{s['median']:.4f}",
                f"{s['mean']:.4f}",
                f"{s['max']:.4f}",
            ])
        id_rows.append(["Balanced Accuracy", "—", "—", f"{ic['balanced_accuracy']:.4f}", "—"])

        t = Table(id_rows, colWidths=[5 * cm, 3 * cm, 3 * cm, 3 * cm, 3 * cm])
        t.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0), DARK),
            ("TEXTCOLOR",     (0, 0), (-1, 0), colors.white),
            ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",      (0, 0), (-1, -1), 9),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT]),
            ("GRID",          (0, 0), (-1, -1), 0.25, GREY),
            ("TOPPADDING",    (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING",   (0, 0), (-1, -1), 8),
            ("ALIGN",         (1, 0), (-1, -1), "CENTER"),
        ]))
        story.append(t)
        story.append(Spacer(1, 0.5 * cm))

        # Per-class F1 bar chart
        img_f1 = _safe_image(f1_path, page_w, 14 * cm)
        if img_f1:
            story.append(img_f1)
            story.append(Paragraph(
                "Per-class F1 scores: best and worst classes (up to 40 each).",
                styles["caption"],
            ))

        story.append(PageBreak())

        # ==================================================================
        # CONFUSION MATRIX
        # ==================================================================
        story.append(Paragraph("Confusion Matrix (ID classes)", styles["h1"]))
        story.append(HRFlowable(width="100%", thickness=0.5, color=GREY, spaceAfter=6))
        story.append(Paragraph(
            "Row-normalised heatmap — colour encodes per-class recall.  "
            "A raw-count CSV is saved alongside this report.",
            styles["body"],
        ))
        story.append(Spacer(1, 0.3 * cm))

        img_cm = _safe_image(cm_path, page_w, 18 * cm)
        if img_cm:
            story.append(img_cm)
            story.append(Paragraph("Confusion matrix (row-normalised).", styles["caption"]))

        # ==================================================================
        # EXTRA METHOD-SPECIFIC FIGURES
        # ==================================================================
        if extra_figures:
            story.append(PageBreak())
            story.append(Paragraph("Method-Specific Figures", styles["h1"]))
            story.append(HRFlowable(width="100%", thickness=0.5, color=GREY, spaceAfter=6))

            for fig_path in extra_figures:
                img = _safe_image(fig_path, page_w, 14 * cm)
                if img:
                    story.append(img)
                    story.append(Paragraph(
                        os.path.basename(fig_path), styles["caption"]
                    ))
                    story.append(Spacer(1, 0.4 * cm))
                else:
                    story.append(Paragraph(
                        f"<i>(Figure not found: {fig_path})</i>", styles["body"]
                    ))

        # ==================================================================
        # BUILD PDF
        # ==================================================================
        pdf_name = (
            f"ood_report_{m.dataset_name}_{m.setup}_"
            f"abund{m.abundance_filter}_{tag}.pdf"
        ).replace(" ", "_").replace("/", "-")
        pdf_path = os.path.join(self.output_dir, pdf_name)

        cb = _make_page_callbacks(method_name, tag)

        doc = SimpleDocTemplate(
            pdf_path,
            pagesize     = A4,
            topMargin    = 1.8 * cm,
            bottomMargin = 1.4 * cm,
            leftMargin   = 2 * cm,
            rightMargin  = 2 * cm,
            onFirstPage  = cb,
            onLaterPages = cb,
        )
        doc.build(story)
        print(f"[OODReport] Report saved → {pdf_path}")
        return pdf_path