main:
  name: "DRIAMS_experiment_ABUNDANCE_5"
  write_interval: "epoch"
  output_dir: "./output/driams_abundance_5"
  verbose: true
  cpus: 2
  seed: 24

dataset:
  name: "DRIAMS"
  data_dir: "./data/"
  data_file: "DRIAMS_filt.h5"
  
  # Class filtering
  min_samples_per_class: 30
  abundance_percentage: 5
  
  # Data splitting
  batch_size: 512
  validation_size: 0.2
  test_size: 0.2

ood:
  train: False
  train_ood: False
  setup: "abundance"  # Options: "mix", "abundance", "hierarchy"
  hierarchy_level: None
  hierarchy_leaveout: None
  method: "logitnorm" # Options: "knn", "maha", "msp", "logitnorm", "energy", "energy_maha" "deep_ensemble", "gmm"
  knn_variant: "embedding" # Options: "raw", "pca", "embedding"